version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:13.7.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start build"
      - run: yarn install
      - run: yarn build -- --prod --aot --extract-css --build-optimizer --optimization
  lint:
    docker:
      - image: circleci/node:13.7.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start lint"
      - run: yarn install
      - run: yarn lint
  test:
    docker:
      - image: circleci/node:13.7.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start test"
      - run: npm install
      - run: npm run test -- --no-watch --no-progress
  e2e:
    docker:
      - image: circleci/node:13.7.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start e2e"
      - run: npm install
      - run: npm run e2e -- --protractor-config=e2e/protractor.conf.js
  deploy:
    docker:
      - image: circleci/node:13.7.0-stretch-browsers
    steps:
      - checkout
      - run: echo "Start deploy"
      - run: npm install
      - run: npm run build
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - lint:
          requires:
            - build
      - test:
          requires:
            - build
      - e2e:
          requires:
            - build
      - deploy:
          requires:
            - lint
            - test
            - e2e
